import React from 'react';
import {
  Plus,
  X,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  ArrowLeft,
  ArrowRight,
  RotateCw,
  PanelLeft,
  Share,
  LayoutGrid,
  Type,
  Calendar,
  Bell,
  CheckCircle,
  Bookmark,
  BookmarkCheck,
  Clock,
  Download,
  Search,
  Lock,
  Globe,
  Star,
  Zap,
  Settings,
  Eye,
  EyeOff,
  Volume2,
  VolumeOff,
  Moon,
  Folder,
  FolderOpen,
  Trash2,
  ExternalLink,
  Pin,
  PinOff,
  FileText,
  Shield,
  Puzzle,
  Keyboard,
  Palette,
  Pause,
  Play,
  ArrowDownCircle,
  Minus,
  Square,
  Copy,
  Layers,
  ALargeSmall,
  Home,
  Info,
  Check,
  ShieldCheck,
  ShieldOff,
  Fingerprint,
  Cookie,
  MoreVertical,
  AppWindow,
  Sparkles,
  Wallet,
  KeyRound,
  Maximize,
  Printer,
  Wrench,
  Share2,
  Terminal,
  Code,
  Cpu,
  Sun,
  Monitor,
  SlidersHorizontal,
  Database,
  Bug,
  Command,
  Pencil,
  Heart,
  Lightbulb,
  Smile,
  Cloud,
  Crown,
  Coffee,
  Rocket,
  Paperclip,
  Flame,
  Brush,
  type LucideIcon,
} from 'lucide-react';

/**
 * Mapping from legacy icon names to Lucide components.
 * Keeps the same `<Icon name="..." />` API so all existing consumers work unchanged.
 */
const ICON_MAP: Record<string, LucideIcon> = {
  plus: Plus,
  x: X,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-clockwise': RotateCw,
  sidebar: PanelLeft,
  'safari-share': Share,
  'tabs-overview': LayoutGrid,
  'format-aa': Type,
  calendar: Calendar,
  bell: Bell,
  'check-circle': CheckCircle,
  bookmark: Bookmark,
  'bookmark-fill': BookmarkCheck,
  clock: Clock,
  download: Download,
  search: Search,
  lock: Lock,
  globe: Globe,
  star: Star,
  bolt: Zap,
  gear: Settings,
  eye: Eye,
  'eye-slash': EyeOff,
  speaker: Volume2,
  'speaker-slash': VolumeOff,
  moon: Moon,
  folder: Folder,
  'folder-open': FolderOpen,
  trash: Trash2,
  external: ExternalLink,
  pin: Pin,
  'pin-fill': PinOff,
  doc: FileText,
  shield: Shield,
  puzzle: Puzzle,
  keyboard: Keyboard,
  palette: Palette,
  pause: Pause,
  play: Play,
  'arrow-down-circle': ArrowDownCircle,
  minus: Minus,
  square: Square,
  copy: Copy,
  layers: Layers,
  'text-size': ALargeSmall,
  home: Home,
  info: Info,
  check: Check,
  'shield-check': ShieldCheck,
  'shield-x': ShieldOff,
  fingerprint: Fingerprint,
  cookie: Cookie,
  zap: Zap,
  'dots-vertical': MoreVertical,
  window: AppWindow,
  sparkles: Sparkles,
  wallet: Wallet,
  key: KeyRound,
  fullscreen: Maximize,
  printer: Printer,
  wrench: Wrench,
  share: Share2,
  terminal: Terminal,
  code: Code,
  cpu: Cpu,
  sun: Sun,
  monitor: Monitor,
  sliders: SlidersHorizontal,
  database: Database,
  bug: Bug,
  command: Command,
  pencil: Pencil,
  // Doodle icons mapped to closest Lucide equivalents
  'doodle-star': Star,
  'doodle-heart': Heart,
  'doodle-sparkle': Sparkles,
  'doodle-lightbulb': Lightbulb,
  'doodle-smile': Smile,
  'doodle-cloud': Cloud,
  'doodle-pin': Pin,
  'doodle-crown': Crown,
  'doodle-coffee': Coffee,
  'doodle-rocket': Rocket,
  'doodle-paperclip': Paperclip,
  'doodle-squiggle': Minus,
  'doodle-arrow-curved': ArrowRight,
  'doodle-flame': Flame,
  'doodle-brush': Brush,
};

export type IconName = keyof typeof ICON_MAP;

export function Icon({
  name,
  size = 16,
  strokeWidth = 1.5,
  className = '',
  style,
}: {
  name: IconName;
  size?: number;
  strokeWidth?: number;
  className?: string;
  style?: React.CSSProperties;
}) {
  const LucideComponent = ICON_MAP[name] || SlidersHorizontal;
  return (
    <LucideComponent
      size={size}
      strokeWidth={strokeWidth}
      className={className}
      style={style}
      aria-hidden
    />
  );
}
